
app:
  build: .
  command: python3.9 app.py
  ports:
    - "5000:5000"
    - "5001:5001"
  links:
    - db
db:
  image: mongo:latest
  hostname: test_db
  environment:
    - MONGO_INITDB_DATABASE=nacool_projects
  ports:
    - 27017:27017
